package com.gubang.dao;

import com.gubang.entity.ProductDetailInfo;

public interface ProductDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    int insert(ProductDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    int insertSelective(ProductDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    ProductDetailInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    int updateByPrimaryKeySelective(ProductDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    int updateByPrimaryKey(ProductDetailInfo record);
    
    /**
     * 根据产品的条形码查询产品的详细信息
     */
    ProductDetailInfo selectByProductBarcode(String barcode);
}