package com.gubang.entity;

import java.util.Date;

public class ProductListInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_list.id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_list.barcode
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_list.product_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_list.create_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_list.create_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_list.update_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_list.update_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_list.is_delete
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_list.id
     *
     * @return the value of product_list.id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_list.id
     *
     * @param id the value for product_list.id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_list.barcode
     *
     * @return the value of product_list.barcode
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_list.barcode
     *
     * @param barcode the value for product_list.barcode
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_list.product_id
     *
     * @return the value of product_list.product_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_list.product_id
     *
     * @param productId the value for product_list.product_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_list.create_time
     *
     * @return the value of product_list.create_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_list.create_time
     *
     * @param createTime the value for product_list.create_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_list.create_user_id
     *
     * @return the value of product_list.create_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_list.create_user_id
     *
     * @param createUserId the value for product_list.create_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_list.update_time
     *
     * @return the value of product_list.update_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_list.update_time
     *
     * @param updateTime the value for product_list.update_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_list.update_user_id
     *
     * @return the value of product_list.update_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_list.update_user_id
     *
     * @param updateUserId the value for product_list.update_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_list.is_delete
     *
     * @return the value of product_list.is_delete
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_list.is_delete
     *
     * @param isDelete the value for product_list.is_delete
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}