package com.gubang.entity;

import java.util.Date;

public class ProductDetailInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.series
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String series;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.name
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.machine_code
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String machineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.voltage_range
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String voltageRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.distribute_price
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Double distributePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.retail_price
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Double retailPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.function_descp
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String functionDescp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.policy
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String policy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.create_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.create_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.update_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.update_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail.is_delete
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.id
     *
     * @return the value of product_detail.id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.id
     *
     * @param id the value for product_detail.id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.series
     *
     * @return the value of product_detail.series
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.series
     *
     * @param series the value for product_detail.series
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setSeries(String series) {
        this.series = series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.name
     *
     * @return the value of product_detail.name
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.name
     *
     * @param name the value for product_detail.name
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.machine_code
     *
     * @return the value of product_detail.machine_code
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getMachineCode() {
        return machineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.machine_code
     *
     * @param machineCode the value for product_detail.machine_code
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setMachineCode(String machineCode) {
        this.machineCode = machineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.voltage_range
     *
     * @return the value of product_detail.voltage_range
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getVoltageRange() {
        return voltageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.voltage_range
     *
     * @param voltageRange the value for product_detail.voltage_range
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setVoltageRange(String voltageRange) {
        this.voltageRange = voltageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.distribute_price
     *
     * @return the value of product_detail.distribute_price
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Double getDistributePrice() {
        return distributePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.distribute_price
     *
     * @param distributePrice the value for product_detail.distribute_price
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setDistributePrice(Double distributePrice) {
        this.distributePrice = distributePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.retail_price
     *
     * @return the value of product_detail.retail_price
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Double getRetailPrice() {
        return retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.retail_price
     *
     * @param retailPrice the value for product_detail.retail_price
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setRetailPrice(Double retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.function_descp
     *
     * @return the value of product_detail.function_descp
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getFunctionDescp() {
        return functionDescp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.function_descp
     *
     * @param functionDescp the value for product_detail.function_descp
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setFunctionDescp(String functionDescp) {
        this.functionDescp = functionDescp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.policy
     *
     * @return the value of product_detail.policy
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getPolicy() {
        return policy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.policy
     *
     * @param policy the value for product_detail.policy
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setPolicy(String policy) {
        this.policy = policy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.create_time
     *
     * @return the value of product_detail.create_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.create_time
     *
     * @param createTime the value for product_detail.create_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.create_user_id
     *
     * @return the value of product_detail.create_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.create_user_id
     *
     * @param createUserId the value for product_detail.create_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.update_time
     *
     * @return the value of product_detail.update_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.update_time
     *
     * @param updateTime the value for product_detail.update_time
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.update_user_id
     *
     * @return the value of product_detail.update_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.update_user_id
     *
     * @param updateUserId the value for product_detail.update_user_id
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail.is_delete
     *
     * @return the value of product_detail.is_delete
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail.is_delete
     *
     * @param isDelete the value for product_detail.is_delete
     *
     * @mbg.generated Sun Dec 10 14:18:31 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}